# Challenge 1: Bar Chart Race avec Fourish Studio
___

In [ ]:
# Les librairies suivantes ont été importées pour vous. Exécutez le code.

# Librairies qui nous serviront à extraire des données depuis une page Web (scraper)

from bs4 import BeautifulSoup
from requests import get


# Vous connaissez déjà ces librairies, n'est-ce pas? :)

import pandas as pd
from time import sleep
import numpy as np

### Lecture du fichier .csv

Lire le fichier .csv à l'aide de pandas et appeler le dataframe <b>pop_df</b>.

In [ ]:
# Importez, lisez et afficher les 5 premières lignes du fichier .csv à l'aide de pandas et appeler le dataframe 'pop_df'.
pop_df = pd.read_csv("population_total.csv")
pop_df.head()

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,76600000,76400000,76300000,76100000,76000000,75800000,75600000,75400000,75200000,74900000
1,Albania,400000,402000,404000,405000,407000,409000,411000,413000,414000,...,1330000,1300000,1270000,1250000,1220000,1190000,1170000,1140000,1110000,1090000
2,Algeria,2500000,2510000,2520000,2530000,2540000,2550000,2560000,2560000,2570000,...,70400000,70500000,70500000,70600000,70700000,70700000,70700000,70700000,70700000,70700000
3,Andorra,2650,2650,2650,2650,2650,2650,2650,2650,2650,...,63000,62900,62900,62800,62700,62700,62600,62500,62500,62400
4,Angola,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,...,168000000,170000000,172000000,175000000,177000000,179000000,182000000,184000000,186000000,188000000

---

### Web Scraping en action !!!

In [ ]:
# Le code suivant nous permet de pointer sur le site web sur lequel nous désirons extraire/collecter les données (countryflags.com)
# Exécutez le code.

url = "https://www.countryflags.com/"
response = get(url)

html_soup = BeautifulSoup(response.text, 'html.parser')

1) <b>Que contient l'objet 'html_soup' selon vous?</b> <br/>
Votre réponse ici: code source du site

In [ ]:
# Le code suivant nous permet d'extraire/collecter les données depuis le site countryflags.com.
# Exécutez le code.

containers = html_soup.find_all('div', class_='thumb')
for container in containers: 
  try:
    country_name = container.find('span', class_='title').text[8:]
    country_flag_url = container.find('img')['src']
    print(country_name, end=" ")
    print(country_flag_url)
    sleep(0.05)
  except:
    pass

<b>2) Quelles données avons-nous collecté depuis le site countryflags.com ? </b><br />
Votre réponse ici: Les adresses URL des différents drapeaux

---

### À vous de jouer !!!

In [ ]:
# Réutilisez le code de la cellule ci-dessus et stockez le nom des pays dans une liste appelée 'countries_name' et les urls des drapeaux dans une liste appelée 'countries_flag'

containers = html_soup.find_all('div', class_='thumb')
countries_name = []
countries_flag = []
for container in containers: 
  try:
    country_name = container.find('span', class_='title').text[8:]
    country_flag_url = container.find('img')['src']
    countries_name.append(country_name)
    countries_flag.append(country_flag_url)
    #print(country_name, end=" ")
    #print(country_flag_url)
    #sleep(0.05)
  except:
    pass
print(countries_name)
print(countries_flag)

['China', 'India', 'Europe', 'the Arab League', 'United States, the', 'Indonesia', 'Brazil', 'Pakistan', 'Nigeria', 'Bangladesh', 'Russia', 'Japan', 'Mexico', 'Ethiopia', 'Philippines, the', 'Egypt', 'Vietnam', 'Congo, Democratic Republic of the', 'Iran', 'Turkey', 'Germany', 'Thailand', 'United Kingdom, the', 'France', 'Italy', 'Myanmar', 'England', 'South Africa', 'Tanzania', 'Korea, South', 'Spain', 'Colombia', 'Kenya', 'Argentina', 'Ukraine', 'Algeria', 'Uganda', 'Iraq', 'Poland', 'Sudan', 'Canada', 'Afghanistan', 'Morocco', 'Malaysia', 'Venezuela', 'Peru', 'Uzbekistan', 'Nepal', 'Angola', 'Saudi Arabia', 'Yemen', 'Ghana', 'Mozambique', 'Korea, North', 'Madagascar', 'Cameroon', 'Côte d’ Ivoire', 'Taiwan', 'Australia', 'Sri Lanka', 'Romania', 'Burkina Faso', 'Syria', 'Niger', 'Malawi', 'Kazakhstan', 'Mali', 'Chile', 'Netherlands, the', 'Ecuador', 'Cambodia', 'Zambia', 'Guatemala', 'Senegal', 'Zimbabwe', 'South Sudan', 'Guinea', 'Chad', 'Rwanda', 'Belgium', 'Burundi', 'Tunisia', 'Cuba', 'Bolivia', 'Benin', 'Somalia', 'Portugal', 'Greece', 'Dominican Republic, the', 'Czech Republic, the', 'Haiti', 'Jordan', 'Azerbaijan', 'Sweden', 'Hungary', 'Belarus', 'Israel', 'Honduras', 'Austria', 'Tajikistan', 'Switzerland', 'Togo', 'Hong Kong', 'Laos', 'Serbia', 'Bulgaria', 'Paraguay', 'Papua New Guinea', 'Libya', 'Lebanon', 'El Salvador', 'Sierra Leone', 'United Arab Emirates, the', 'Nicaragua', 'Eritrea', 'Singapore', 'Kyrgyzstan', 'Central-African Republic, the', 'Denmark', 'Finland', 'Slovakia', 'Turkmenistan', 'Norway', 'Scotland', 'Ireland', 'Congo, Republic of the', 'Costa Rica', 'Georgia', 'Liberia', 'Palestine', 'New Zealand', 'Croatia', 'Mauritania', 'Panama', 'Bosnia and Herzegovina', 'Moldova', 'Oman', 'Uruguay', 'Puerto Rico', 'Mongolia', 'Wales', 'Albania', 'Armenia', 'Jamaica', 'Kuwait', 'Lithuania', 'Namibia', 'Qatar', 'Botswana', 'North Macedonia', 'Gambia, the', 'Slovenia', 'Lesotho', 'Latvia', 'Kosovo', 'Saint Patrick', 'Northern Ireland', 'Guinea-Bissau', 'Gabon', 'Swaziland', 'Bahrain', 'Mauritius', 'East Timor', 'Estonia', 'Cyprus', 'Trinidad and Tobago', 'Fiji', 'Djibouti', 'Comoros', 'Equatorial Guinea', 'Bhutan', 'Guyana', 'Solomon Islands, the', 'Montenegro', 'Macao', 'Luxembourg', 'Suriname', 'Cape Verde', 'Brunei', 'Malta', 'Guadeloupe', 'Maldives, the', 'Belize', 'Iceland', 'Bahamas, the', 'Barbados', 'Vanuatu', 'New Caledonia', 'São Tomé and Príncipe', 'Samoa', 'Guam', 'Saint Lucia', 'Curaçao', 'Aruba', 'Grenada', 'Kiribati', 'Tonga', 'Micronesia', 'Saint Vincent and the Grenadines', 'Antigua and Barbuda', 'Seychelles, the', 'Andorra', 'Marshall Islands, the', 'Dominica', 'Greenland', 'Saint Kitts and Nevis', 'the Northern Mariana Islands', 'the Faroe Islands', 'St. Martin', 'Liechtenstein', 'San Marino', 'Monaco', 'Palau', 'Bonaire', 'Tuvalu', 'Nauru', 'St. Eustatius', 'Saba', 'Niue', 'Vatican City']
['https://cdn.countryflags.com/thumbs/china/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/india/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/europe/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/arab-league/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/indonesia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/brazil/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/pakistan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/nigeria/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bangladesh/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/russia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/japan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mexico/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/ethiopia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/philippines/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/egypt/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/vietnam/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/iran/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/turkey/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/germany/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/thailand/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/united-kingdom/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/france/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/italy/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/myanmar/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/england/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/south-africa/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/tanzania/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/south-korea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/spain/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/colombia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kenya/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/argentina/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/ukraine/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/algeria/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/uganda/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/iraq/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/poland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/sudan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/canada/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/afghanistan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/morocco/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/malaysia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/venezuela/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/peru/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/uzbekistan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/nepal/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/angola/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/saudi-arabia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/yemen/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/ghana/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mozambique/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/north-korea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/madagascar/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cameroon/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cote-d-ivoire/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/taiwan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/australia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/sri-lanka/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/romania/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/burkina-faso/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/syria/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/niger/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/malawi/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kazakhstan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mali/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/chile/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/netherlands/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/ecuador/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cambodia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/zambia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guatemala/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/senegal/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/zimbabwe/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/south-sudan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guinea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/chad/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/rwanda/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/belgium/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/burundi/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/tunisia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cuba/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bolivia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/benin/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/somalia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/portugal/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/greece/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/dominican-republic/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/czech-republic/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/haiti/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/jordan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/azerbaijan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/sweden/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/hungary/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/belarus/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/israel/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/honduras/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/austria/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/tajikistan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/switzerland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/togo/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/hongkong/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/laos/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/serbia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bulgaria/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/paraguay/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/papua-new-guinea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/libya/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/lebanon/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/el-salvador/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/sierra-leone/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/united-arab-emirates/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/nicaragua/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/eritrea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/singapore/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kyrgyzstan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/central-african-republic/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/denmark/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/finland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/slovakia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/turkmenistan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/norway/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/scotland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/ireland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/congo-republic-of-the/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/costa-rica/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/georgia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/liberia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/palestine/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/new-zealand/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/croatia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mauritania/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/panama/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/moldova/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/oman/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/uruguay/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/puerto-rico/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mongolia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/wales/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/albania/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/armenia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/jamaica/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kuwait/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/lithuania/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/namibia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/qatar/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/botswana/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/north-macedonia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/gambia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/slovenia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/lesotho/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/latvia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kosovo/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/st-patrick/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/northern-ireland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guinea-bissau/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/gabon/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/swaziland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bahrain/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/mauritius/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/east-timor/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/estonia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cyprus/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/fiji/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/djibouti/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/comoros/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/equatorial-guinea/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bhutan/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guyana/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/solomon-islands/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/montenegro/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/macau/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/luxembourg/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/suriname/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/cape-verde/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/brunei/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/malta/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guadeloupe/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/maldives/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/belize/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/iceland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bahamas/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/barbados/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/vanuatu/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/new-caledonia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/samoa/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/guam/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/saint-lucia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/curacao/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/aruba/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/grenada/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/kiribati/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/tonga/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/micronesia/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/saint-vincent-and-the-grenadines/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/antigua-and-barbuda/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/seychelles/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/andorra/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/marshall-islands/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/dominica/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/greenland/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/saint-kitts-and-nevis/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/northern-mariana-islands/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/faroe-islands/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/st-martin/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/liechtenstein/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/san-marino/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/monaco/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/palau/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/bonaire/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/tuvalu/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/nauru/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/st-eustatius/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/saba/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/niue/flag-square-250.png', 'https://cdn.countryflags.com/thumbs/vatican-city/flag-square-250.png']

In [ ]:
# Créez un dataframe 'df_countries_flag' à partir de nos listes 'countries_name' et 'countries_flag'.

#df_countries_flag = pd.DataFrame({"countries" : countries_name, "flags" : countries_flag})
df_countries_flag = pd.DataFrame(list(zip(countries_name, countries_flag)), columns = ["country_name", "country_flag"])
df_countries_flag.head()

         country_name                                       country_flag
0               China  https://cdn.countryflags.com/thumbs/china/flag...
1               India  https://cdn.countryflags.com/thumbs/india/flag...
2              Europe  https://cdn.countryflags.com/thumbs/europe/fla...
3     the Arab League  https://cdn.countryflags.com/thumbs/arab-leagu...
4  United States, the  https://cdn.countryflags.com/thumbs/united-sta...

### Feature Engineering

In [ ]:
# Le code suivant vérifie si le nom d'un pays est présent à la fois dans le dataset 'pop_df' et 'df_countries_flag'. Si c'est le cas, alors l'url
# du drapeau du pays est transféré dans le dataset 'pop_df', dans une nouvelle colonne appelée 'url_flag'. Dans le cas contraire, la valeur -1 sera
# ajoutée. Le code applique cela à tous les pays du dataset 'pop_df'.

pop_df['url_flag'] = (pop_df.country.apply(lambda x: df_countries_flag.query('@x in country_name').index.values)
                         .apply(lambda x: x[0] if len(x) else -1)).apply(lambda x: df_countries_flag.country_flag[x] if x != -1 else x)

In [ ]:
# Afficher le dataset de nouveau

pop_df.head()

,country,region,1800,1801,1802,1803,1804,1805,1806,1807,...,2092,2093,2094,2095,2096,2097,2098,2099,2100,url_flag
0,Afghanistan,Asia,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,76400000,76300000,76100000,76000000,75800000,75600000,75400000,75200000,74900000,https://cdn.countryflags.com/thumbs/afghanista...
1,Albania,Europe,400000,402000,404000,405000,407000,409000,411000,413000,...,1300000,1270000,1250000,1220000,1190000,1170000,1140000,1110000,1090000,https://cdn.countryflags.com/thumbs/albania/fl...
2,Algeria,Africa,2500000,2510000,2520000,2530000,2540000,2550000,2560000,2560000,...,70500000,70500000,70600000,70700000,70700000,70700000,70700000,70700000,70700000,https://cdn.countryflags.com/thumbs/algeria/fl...
3,Andorra,Europe,2650,2650,2650,2650,2650,2650,2650,2650,...,62900,62900,62800,62700,62700,62600,62500,62500,62400,https://cdn.countryflags.com/thumbs/andorra/fl...
4,Angola,Africa,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,...,170000000,172000000,175000000,177000000,179000000,182000000,184000000,186000000,188000000,https://cdn.countryflags.com/thumbs/angola/fla...

Trouvez la colonne <b>url_flag</b>

Nous allons maintenant ajouter une colonne 'region' dans notre dataframe 'pop_df' selon les règles suivantes:
* Asia -> AS
* Americas -> AM
* Africa -> AF
* Europe -> EU <br />

Pour cela, vous devrez installer, importer et utiliser la librairie [pycountry-convert](https://pypi.org/project/pycountry-convert/) qui permet, entre autres, de trouver le code continent associé à un pays. Pour installer la librairie, exécutez ce code: <br />


```
!pip install pycountry-convert
```

Prenez le temps de prendre connaissance de la documentation de cette librairie 
afin d'obtenir le résultat escompté.

In [ ]:
# Installez la librairie pycountry-convert
!pip install pycountry-convert

In [ ]:
# importez la librairie pycountry-convert ici.
import pycountry_convert as pc

<i>Aide: Une fois les codes continents de chaque pays récupérés et insérés dans la colonne <b>region</b> de notre dataset <b>pop_df</b>, les convertir en <b>4 regions</b> (cf. instructions ci-dessus). Nous utiliserons le nom complet des régions afin de les utiliser en légende de notre visualisation.</i>

In [ ]:
# Extraire la colonne 'country' depuis notre dataframe et la transformer en liste
liste_countries_name = list(pop_df["country"])

In [ ]:
# Utilisez la librairie pycountry_convert afin d'associer chaque pays à son code continent. 
# Indice: nous utiliserons ici le format 'alpha2' pour obtenir de meilleurs résultats.
# Afin d'éviter tout arrêt d'exécution de notre code en cas de "non match", utilisez les instructions (statements) 'try except'.
liste_countries_ISO = []
for country in liste_countries_name:
  try:
    liste_countries_ISO.append(pc.country_name_to_country_alpha2(country))
  except:
    liste_countries_ISO.append("NaN")

liste_continents_ISO = []
for ISO in liste_countries_ISO:
  try:
    liste_continents_ISO.append(pc.country_alpha2_to_continent_code(ISO))
  except:
    liste_continents_ISO.append("NaN")

In [ ]:
# Créez un nouveau dataframe qui contiendra les noms des pays et codes continents
# Pour cela, la fonction zip() pourra vous être utile. Documentez-vous pour comprendre comment l'utiliser.

pop_df_2 = pd.DataFrame(list(zip(liste_countries_name, liste_continents_ISO)), columns = ["country_name", "continent_code"])
pop_df_2.head

<bound method NDFrame.head of     country_name continent_code
0    Afghanistan             AS
1        Albania             EU
2        Algeria             AF
3        Andorra             EU
4         Angola             AF
..           ...            ...
190    Venezuela             SA
191      Vietnam             AS
192        Yemen             AS
193       Zambia             AF
194     Zimbabwe             AF

[195 rows x 2 columns]>

In [ ]:
# Trouver une méthode avec pandas afin d'extraire la liste des continents UNIQUES de notre nouveau dataframe.
# Il y a t-il des valeurs non renseignées ('NaN')?? Si oui, notre prochaine mission sera de les transformer.

pop_df_2["continent_code"].unique()

array(['AS', 'EU', 'AF', 'NA', 'SA', 'OC', 'NaN'], dtype=object)

In [ ]:
# Faire un filtre (masque) afin de trouver toutes les lignes de notre dataframe contenant des NaN dans la colonne des codes continents.
mask = pop_df_2["continent_code"] == "NaN"
a = pop_df_2[mask]
a

                       country_name continent_code
38                 Congo, Dem. Rep.            NaN
39                      Congo, Rep.            NaN
41                    Cote d'Ivoire            NaN
73                         Holy See            NaN
92                              Lao            NaN
111           Micronesia, Fed. Sts.            NaN
165  St. Vincent and the Grenadines            NaN
174                     Timor-Leste            NaN

In [ ]:
# Il y a peu de 'NaN'. Nous allons donc pouvoir les remplacer manuellement dans notre liste 'continent_code'.
# Pour cela, recupérez le numéro de ligne (index) de notre dataframe pour les codes continents ayant pour valeur 'NaN'.
# À partir de ces index, remplacer les 'NaN' de notre liste 'continent_code' par les éléments de la liste ci-dessous:

missing_continent_code = pop_df_2[pop_df_2["continent_code"] == "NaN"].index.tolist()
continents_to_add = ['AF', 'AF', 'AF', 'EU', 'AS', 'OC', 'NA', 'AS']

for index in range(len(missing_continent_code)):
  pop_df_2.iloc[missing_continent_code[index]]["continent_code"] = continents_to_add[index]

pop_df_2.head()

  country_name continent_code
0  Afghanistan             AS
1      Albania             EU
2      Algeria             AF
3      Andorra             EU
4       Angola             AF

In [ ]:
# Une fois la manipulation faite, reste t-il des 'NaN' dans notre liste?
 NOP

In [ ]:
# Insérez la nouvelle liste 'continent_code' en 2ème colonne de notre dataframe 'pop_df'.
# Pour cela, vous pourrez utiliser la méthode '.insert()'

liste_continent_code = list(pop_df_2["continent_code"])

#pop_df.insert(1, "continent_code", liste_continent_code)
pop_df.head()

,country,continent_code,1800,1801,1802,1803,1804,1805,1806,1807,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,AS,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,76600000,76400000,76300000,76100000,76000000,75800000,75600000,75400000,75200000,74900000
1,Albania,EU,400000,402000,404000,405000,407000,409000,411000,413000,...,1330000,1300000,1270000,1250000,1220000,1190000,1170000,1140000,1110000,1090000
2,Algeria,AF,2500000,2510000,2520000,2530000,2540000,2550000,2560000,2560000,...,70400000,70500000,70500000,70600000,70700000,70700000,70700000,70700000,70700000,70700000
3,Andorra,EU,2650,2650,2650,2650,2650,2650,2650,2650,...,63000,62900,62900,62800,62700,62700,62600,62500,62500,62400
4,Angola,AF,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,...,168000000,170000000,172000000,175000000,177000000,179000000,182000000,184000000,186000000,188000000

In [ ]:
# Afin de limiter le nombre le labels dans notre visualisation, transformez les codes continents en 4 régions du monde 
# ('Asia', 'Europe', 'Africa', 'Americas'). Pour cela, comprenez et exécutez le code suivant:

pop_df.loc[pop_df['continent_code'] == 'NA', 'continent_code'] = 'AM'
pop_df.loc[pop_df['continent_code'] == 'SA', 'continent_code'] = 'AM'
pop_df.loc[pop_df['continent_code'] == 'OC', 'continent_code'] = 'AS'

pop_df.loc[pop_df['continent_code'] == 'AS', 'continent_code'] = 'Asia'
pop_df.loc[pop_df['continent_code'] == 'EU', 'continent_code'] = 'Europe'
pop_df.loc[pop_df['continent_code'] == 'AF', 'continent_code'] = 'Africa'
pop_df.loc[pop_df['continent_code'] == 'AM', 'continent_code'] = 'Americas'

In [ ]:
# Affichez le dataframe final

#pop_df.rename(columns = {"continent_code":"region"}, inplace=True)
pop_df

,country,region,1800,1801,1802,1803,1804,1805,1806,1807,...,2092,2093,2094,2095,2096,2097,2098,2099,2100,url_flag
0,Afghanistan,Asia,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,76400000,76300000,76100000,76000000,75800000,75600000,75400000,75200000,74900000,https://cdn.countryflags.com/thumbs/afghanista...
1,Albania,Europe,400000,402000,404000,405000,407000,409000,411000,413000,...,1300000,1270000,1250000,1220000,1190000,1170000,1140000,1110000,1090000,https://cdn.countryflags.com/thumbs/albania/fl...
2,Algeria,Africa,2500000,2510000,2520000,2530000,2540000,2550000,2560000,2560000,...,70500000,70500000,70600000,70700000,70700000,70700000,70700000,70700000,70700000,https://cdn.countryflags.com/thumbs/algeria/fl...
3,Andorra,Europe,2650,2650,2650,2650,2650,2650,2650,2650,...,62900,62900,62800,62700,62700,62600,62500,62500,62400,https://cdn.countryflags.com/thumbs/andorra/fl...
4,Angola,Africa,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,...,170000000,172000000,175000000,177000000,179000000,182000000,184000000,186000000,188000000,https://cdn.countryflags.com/thumbs/angola/fla...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,Americas,1000000,978000,957000,936000,916000,896000,876000,857000,...,35400000,35200000,35100000,35000000,34800000,34700000,34500000,34400000,34200000,https://cdn.countryflags.com/thumbs/venezuela/...
191,Vietnam,Asia,4000000,4100000,4200000,4310000,4410000,4530000,4640000,4750000,...,100000000,99700000,99400000,99100000,98800000,98400000,98100000,97800000,97400000,https://cdn.countryflags.com/thumbs/vietnam/fl...
192,Yemen,Asia,2590000,2590000,2590000,2590000,2590000,2590000,2590000,2590000,...,54400000,54300000,54100000,54000000,53800000,53700000,53500000,53400000,53200000,https://cdn.countryflags.com/thumbs/yemen/flag...
193,Zambia,Africa,747000,758000,770000,782000,794000,806000,818000,831000,...,75200000,76000000,76800000,77600000,78400000,79200000,80000000,80800000,81500000,https://cdn.countryflags.com/thumbs/zambia/fla...
194,Zimbabwe,Africa,1090000,1090000,1090000,1090000,1090000,1090000,1090000,1090000,...,30900000,30900000,30900000,30900000,30900000,31000000,31000000,31000000,31000000,https://cdn.countryflags.com/thumbs/zimbabwe/f...

In [ ]:
# Exporter votre dataframe au format .csv (sans les index) et le télécharger.
pop_df.to_csv("my_data.csv", index = False)

---

### La Visualisation !!!

Bon allez, d'accord. <br /> Commencez par créer un compte sur [Flourish Studio](https://flourish.studio/). Une fois connectés :
*   Cliquez sur <b>New visualisation</b> et trouvez le <b>Bar chart race</b> parmi les visualisations disponibles (le premier fera l'affaire)
*   Cliquez sur l'onglet <b>Data</b>
*   Uploadez le fichier .csv que vous avez exporté et téléchargé

Ensuite, à vous de jouer. Naviguez entre les onglets <b>Preview</b> et <b>Data</b> jusqu'à ce que vous obteniez le résultat escompté. <br />Courage ! Vous y êtes presque.

Vous êtes libres de personnaliser votre visualisation comme bon vous semble, cependant, voici quelques règles à respecter:
*   Afficher les 15 premiers pays par défaut
*   Activer l'option permettant de visualiser les 15 derniers pays
*   Un code couleur par région
*   Ajoutez les images de drapeaux, un titre, et une légende (nom complet des régions) à votre visualisation
*   Pour le reste, soyez créatifs !

Satisfait du résultat ? Il est maintenant temps d'afficher votre visualisation sur votre notebook. Pour cela: 



*   Cliquez sur <b>Export & publish</b> depuis [Flourish Studio](https://flourish.studio/)
*   Cliquez ensuite sur <b>Publish to share and embed</b> puis sur <b>Publish</b>
*   Copiez le lien en dessous de la mention <b>Embed on your website</b>
*   Collez le lien dans le code ci-dessous

In [ ]:
from IPython.core.display import HTML
HTML('<div class="flourish-embed flourish-bar-chart-race" data-src="visualisation/9312790"><script src="https://public.flourish.studio/resources/embed.js"></script></div>')

Le résultat ne vous convient pas ? Rien ne vous empêche de modifier de nouveau votre visualisation sur [Flourish Studio](https://flourish.studio/), de cliquer sur <b>Export & publish</b> puis <b>Republish</b>. Copiez de nouveau le lien et le coller de nouveau dans votre notebook. C'est si simple !

<b>BRAVO !</b> Vous avez créer votre premier <b>Bar chart race</b> avec [Flourish Studio](https://flourish.studio/). 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

---